version = "Two"
edition = "2018"
max_width = 100
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
reorder_imports = true
wrap_comments = true
comment_width = 100
